# This macro is needed at the start for building on EL6
%{?nodejs_find_provides_and_requires}



%global barename lodash._basecreatecallback

Name:               nodejs-lodash-basecreatecallback
Version:            2.4.1
Release:            1%{?dist}
Summary:            The internal Lo-Dash function `baseCreateCallback` as a Node.js module

Group:              Development/Libraries
License:            MIT
URL:                https://www.npmjs.org/package/lodash._basecreatecallback
Source0:            http://registry.npmjs.org/%{barename}/-/%{barename}-%{version}.tgz

BuildRequires:      nodejs-packaging >= 6

BuildRequires:      npm(lodash.bind)
BuildRequires:      npm(lodash._setbinddata)
BuildRequires:      npm(lodash.identity)
BuildRequires:      npm(lodash.support)

Requires:           npm(lodash.bind)
Requires:           npm(lodash._setbinddata)
Requires:           npm(lodash.identity)
Requires:           npm(lodash.support)


%description
The internal Lo-Dash function `baseCreateCallback` as a Node.js module
generated by lodash-cli.

%prep
%setup -q -n package

# Remove bundled node_modules if there are any..
rm -rf node_modules/

%nodejs_fixdep lodash.bind ~2.4.x
%nodejs_fixdep lodash._setbinddata ~2.4.x
%nodejs_fixdep lodash.identity ~2.4.x
%nodejs_fixdep lodash.support ~2.4.x





%build
%nodejs_symlink_deps --build

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/lodash._basecreatecallback
cp -pr package.json index.js \
    %{buildroot}%{nodejs_sitelib}/lodash._basecreatecallback

%nodejs_symlink_deps



%files
%doc README.md
%{nodejs_sitelib}/lodash._basecreatecallback/

%changelog
* Tue Jul 08 2014 Ralph Bean <rbean@redhat.com> - 2.4.1-1
- Initial packaging for Fedora.