# This macro is needed at the start for building on EL6
%{?nodejs_find_provides_and_requires}



%global barename lodash.assign

Name:               nodejs-lodash-assign
Version:            2.4.1
Release:            1%{?dist}
Summary:            The Lo-Dash function _.assign as a Node.js module

Group:              Development/Libraries
License:            MIT
URL:                https://www.npmjs.org/package/lodash.assign
Source0:            http://registry.npmjs.org/%{barename}/-/%{barename}-%{version}.tgz

BuildRequires:      nodejs-packaging >= 6

BuildRequires:      npm(lodash.keys)
BuildRequires:      npm(lodash._objecttypes)
BuildRequires:      npm(lodash._basecreatecallback)

Requires:           npm(lodash.keys)
Requires:           npm(lodash._objecttypes)
Requires:           npm(lodash._basecreatecallback)


%description
The Lo-Dash function `_.assign` as a Node.js module generated by lodash-
cli.

%prep
%setup -q -n package

# Remove bundled node_modules if there are any..
rm -rf node_modules/

%nodejs_fixdep --caret



%build
%nodejs_symlink_deps --build

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/lodash.assign
cp -pr package.json index.js \
    %{buildroot}%{nodejs_sitelib}/lodash.assign

%nodejs_symlink_deps



%files
%doc README.md
%{nodejs_sitelib}/lodash.assign/

%changelog
* Tue Jul 08 2014 Ralph Bean <rbean@redhat.com> - 2.4.1-1
- Initial packaging for Fedora.