

%global barename lodash.assign

Name:               nodejs-lodash-assign
Version:            2.4.1
Release:            1%{?dist}
Summary:            The Lo-Dash function _.assign as a Node.js module

Group:              Development/Libraries
License:            MIT
URL:                https://www.npmjs.org/package/lodash.assign
Source0:            http://registry.npmjs.org/%{barename}/-/%{barename}-%{version}.tgz

BuildRequires:      nodejs-packaging >= 6

BuildRequires:      nodejs-lodash-keys
BuildRequires:      nodejs-lodash-objecttypes
BuildRequires:      nodejs-lodash-basecreatecallback

Requires:           nodejs-lodash-keys
Requires:           nodejs-lodash-objecttypes
Requires:           nodejs-lodash-basecreatecallback


%description
The Lo-Dash function `_.assign` as a Node.js module generated by lodash-
cli.

%prep
%setup -q -n package

# Remove bundled node_modules if there are any..
rm -rf node_modules/

%nodejs_fixdep lodash.keys
%nodejs_fixdep lodash._objecttypes
%nodejs_fixdep lodash._basecreatecallback




%build
%nodejs_symlink_deps --build

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/lodash.assign
cp -pr package.json index.js \
    %{buildroot}%{nodejs_sitelib}/lodash.assign

%nodejs_symlink_deps



%files
%doc README.md
%{nodejs_sitelib}/lodash.assign/

%changelog
* Wed Jul 02 2014 Ralph Bean <rbean@redhat.com> - 2.4.1-1
- Initial packaging for Fedora.
